services:
  my-redis-cache:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:7-alpine
    container_name: redis_cache_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
